### ISSUE TITLE
Transition the package to v1.1 of the package template

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#28]
We've just had an email about an update to the package template:

> I have now tagged a new 'release' of the package-template - I called
it v1.1 since the last one was v1.0 (the numbers don't have to be in
sync with the astropy package). I have written up a list of changes
here:

> https://github.com/astropy/package-template/blob/master/TEMPLATE_CHANGES.md#11-2016-06-01

> In particular, note the summary at the bottom of the v1.1 section,
which will help you navigate the changes.

> An example of a pull request to a package to update to the latest
version is here:

> https://github.com/astrofrog/reproject/pull/99

> I would be happy to review any pull requests that carry out this
update, so please just ping me, either on github, or reply to this
email. I'm not going to update any other packages for now, so anyone
can feel free to prepare pull requests for other packages.

> None of the changes are critical, except for the changes to
MANIFEST.in, which will make sure that you don't end up with temporary
files inside astropy-helpers when you release your package.

**Comment by mindriot101** [comment]
The changes:

- [ ] Fixed the import of example_mod.py in init.py to work properly on Python 3. [#167][#167]
- [ ] Fixed the version import in conftest.py to work properly if version.py hasn't been generated yet. [#167][#167]
- [ ] Switch to using container-based builds on Travis. [#133][#133]
- [ ] Entry points are now defined in the setup.cfg file. [#130][#130]
- [ ] Expanded the default .gitignore file. [#146][#146]
- [ ] Switch to using ci-helpers on Travis, and add example AppVeyor config file. [#140][#140]
- [ ] Updated astropy-helpers to v1.1.2. [#147][#147]
- [ ] Remove adjust_compiler from setup.py (this is now dealt with in astropy-helpers). [#154][#154]
- [ ] Update MANIFEST.in to avoid bundling temporary files in astropy-helpers when releasing packages. [#154][#154]
- [ ] Updated ez_setup.py to the latest version. [#135][#135]
- [ ] Catch KeyError when setting up custom test headers in conftest.py. [#143][#143]
- [ ] Update .travis.yml to include testing with the LTS release of Astropy, remove testing against Python 2.6, and update Numpy versions [#148][#148], [#168][#168]
- [ ] Add an example of how to include data in example_subpkg/setup_package.py. [#158][#158]
- [ ] Update ReadTheDocs domains. [#166][#166]
- [ ] Updated Sphinx Makefile. [#171][#171]
- [ ] Updated AppVeyor config to run on Python 2.7 and 3.5. [#170][#170]

[#130]: https://github.com/astropy/package-template/pull/130
[#133]: https://github.com/astropy/package-template/pull/133
[#135]: https://github.com/astropy/package-template/pull/135
[#140]: https://github.com/astropy/package-template/pull/140
[#143]: https://github.com/astropy/package-template/pull/143
[#146]: https://github.com/astropy/package-template/pull/146
[#147]: https://github.com/astropy/package-template/pull/147
[#148]: https://github.com/astropy/package-template/pull/148
[#154]: https://github.com/astropy/package-template/pull/154
[#154]: https://github.com/astropy/package-template/pull/154
[#158]: https://github.com/astropy/package-template/pull/158
[#166]: https://github.com/astropy/package-template/pull/166
[#167]: https://github.com/astropy/package-template/pull/167
[#167]: https://github.com/astropy/package-template/pull/167
[#168]: https://github.com/astropy/package-template/pull/168
[#170]: https://github.com/astropy/package-template/pull/170
[#171]: https://github.com/astropy/package-template/pull/171
